import { SurveySection } from '@/types';

export const SURVEY_SECTIONS: SurveySection[] = [
  {
    id: 'S1',
    title: '학원 기본 정보',
    description: '운영 중이신 학원에 대해 알려주세요',
    questions: [
      {
        id: 'Q1', type: 'single_choice', required: true,
        question: '학원 업종을 선택해 주세요',
        options: [
          { value: 'math', label: '수학' },
          { value: 'english', label: '영어' },
          { value: 'korean', label: '국어/논술' },
          { value: 'science', label: '과학' },
          { value: 'coding', label: '코딩/IT' },
          { value: 'art', label: '미술/음악' },
          { value: 'sports', label: '체육/무용' },
          { value: 'language', label: '외국어(중국어/일본어 등)' },
          { value: 'exam', label: '수능/입시 전문' },
          { value: 'elementary', label: '초등 통합/종합학원' },
          { value: 'kids', label: '유아/어린이' },
          { value: 'adult', label: '성인 교육' },
          { value: 'other', label: '기타', has_input: true },
        ],
      },
      {
        id: 'Q2', type: 'single_choice', required: true,
        question: '학원이 위치한 지역을 선택해 주세요',
        options: [
          { value: 'seoul_gangnam', label: '서울 강남/서초/송파' },
          { value: 'seoul_other', label: '서울 기타 지역' },
          { value: 'gyeonggi_major', label: '경기 주요 도시 (수원, 성남, 고양 등)' },
          { value: 'gyeonggi_other', label: '경기 기타 지역' },
          { value: 'incheon', label: '인천' },
          { value: 'busan_daegu', label: '부산/대구' },
          { value: 'other_metro', label: '기타 광역시' },
          { value: 'other_city', label: '기타 지방 도시/군' },
        ],
      },
      {
        id: 'Q3', type: 'multiple_choice', required: true,
        question: '주요 타겟 학생 연령대를 모두 선택해 주세요',
        options: [
          { value: 'infant', label: '유아 (7세 이하)' },
          { value: 'elementary_low', label: '초등 저학년 (1~3학년)' },
          { value: 'elementary_high', label: '초등 고학년 (4~6학년)' },
          { value: 'middle', label: '중학생' },
          { value: 'high', label: '고등학생' },
          { value: 'adult', label: '성인/직장인' },
        ],
      },
      {
        id: 'Q4', type: 'single_choice', required: true,
        question: '현재 학원 규모(월 수강생 수)를 선택해 주세요',
        options: [
          { value: 'under_30', label: '30명 미만 (소규모/개인 과외형)' },
          { value: '30_100', label: '30~100명' },
          { value: '100_300', label: '100~300명' },
          { value: '300_500', label: '300~500명' },
          { value: 'over_500', label: '500명 이상 (대형)' },
        ],
      },
      {
        id: 'Q5', type: 'single_choice', required: true,
        question: '학원을 운영하신 기간은 얼마나 되셨나요?',
        options: [
          { value: 'under_1', label: '1년 미만 (준비/신규)' },
          { value: '1_3', label: '1~3년' },
          { value: '3_5', label: '3~5년' },
          { value: '5_10', label: '5~10년' },
          { value: 'over_10', label: '10년 이상' },
        ],
      },
    ],
  },
  {
    id: 'S2',
    title: '현재 마케팅 현황',
    description: '지금 진행 중인 마케팅 활동을 알려주세요',
    questions: [
      {
        id: 'Q6', type: 'multiple_choice', required: true,
        question: '현재 사용 중인 온라인 마케팅 채널을 모두 선택해 주세요',
        options: [
          { value: 'naver_blog', label: '네이버 블로그 운영' },
          { value: 'naver_place', label: '네이버 플레이스 등록/관리' },
          { value: 'naver_ad', label: '네이버 검색광고 (키워드 광고)' },
          { value: 'naver_cafe', label: '네이버 카페 운영/홍보' },
          { value: 'instagram', label: '인스타그램 운영' },
          { value: 'meta_ad', label: '페이스북/인스타그램 유료 광고' },
          { value: 'google_ad', label: '구글 광고' },
          { value: 'youtube', label: '유튜브 채널 운영' },
          { value: 'kakao', label: '카카오톡 채널/친구' },
          { value: 'website', label: '학원 자체 홈페이지' },
          { value: 'community', label: '맘카페/지역커뮤니티 홍보' },
          { value: 'sms', label: '문자 마케팅 (SMS/LMS)' },
          { value: 'none', label: '현재 온라인 마케팅 없음' },
        ],
      },
      {
        id: 'Q7', type: 'single_choice', required: true,
        question: '현재 월 마케팅 비용(광고비 포함)은 얼마나 사용하고 계신가요?',
        options: [
          { value: 'zero', label: '거의 없음 (무료 채널만)' },
          { value: 'under_30', label: '30만원 미만' },
          { value: '30_100', label: '30~100만원' },
          { value: '100_300', label: '100~300만원' },
          { value: '300_500', label: '300~500만원' },
          { value: 'over_500', label: '500만원 이상' },
        ],
      },
      {
        id: 'Q8', type: 'single_choice', required: true,
        question: '현재 마케팅의 가장 큰 문제점은 무엇인가요?',
        options: [
          { value: 'no_budget', label: '광고 예산이 부족하다' },
          { value: 'no_knowledge', label: '뭘 해야 할지 모르겠다' },
          { value: 'no_time', label: '직접 할 시간이 없다' },
          { value: 'no_effect', label: '해봤는데 효과가 없었다' },
          { value: 'no_content', label: '콘텐츠 만들기가 어렵다' },
          { value: 'too_expensive', label: '대행 비용이 너무 비싸다' },
          { value: 'no_measure', label: '효과 측정을 못 하겠다' },
          { value: 'no_problem', label: '현재 큰 문제 없음' },
        ],
      },
      {
        id: 'Q9', type: 'single_choice', required: true,
        question: '주로 신규 학생은 어떻게 유입되고 있나요?',
        options: [
          { value: 'word_of_mouth', label: '기존 학생/학부모 입소문' },
          { value: 'naver_search', label: '네이버 검색' },
          { value: 'naver_place', label: '네이버 지도/플레이스' },
          { value: 'sns', label: '인스타그램/SNS' },
          { value: 'leaflet', label: '전단지/현수막 등 오프라인' },
          { value: 'community', label: '맘카페/지역 커뮤니티' },
          { value: 'google', label: '구글 검색' },
          { value: 'mixed', label: '복합적으로 유입' },
          { value: 'dont_know', label: '잘 모르겠다' },
        ],
      },
    ],
  },
  {
    id: 'S3',
    title: '마케팅 목표 및 니즈',
    description: '원하시는 마케팅 방향을 알려주세요',
    questions: [
      {
        id: 'Q10', type: 'multiple_choice', required: true,
        question: '온라인 마케팅을 통해 달성하고 싶은 목표는? (복수 선택)',
        options: [
          { value: 'brand_awareness', label: '학원 인지도/브랜드 향상' },
          { value: 'new_student', label: '신규 원생 모집' },
          { value: 'consultation', label: '상담 문의 증가' },
          { value: 'retention', label: '기존 원생 이탈 방지' },
          { value: 'premium', label: '프리미엄 이미지 구축' },
          { value: 'event', label: '특정 이벤트/시즌 홍보' },
          { value: 'local_domination', label: '지역 내 1위 학원 포지셔닝' },
          { value: 'online_class', label: '온라인 수업 홍보' },
        ],
      },
      {
        id: 'Q11', type: 'single_choice', required: true,
        question: '마케팅에 월 얼마 정도 투자할 의향이 있으신가요?',
        options: [
          { value: 'under_30', label: '30만원 미만 (최소 예산)' },
          { value: '30_50', label: '30~50만원' },
          { value: '50_100', label: '50~100만원' },
          { value: '100_200', label: '100~200만원' },
          { value: '200_300', label: '200~300만원' },
          { value: '300_500', label: '300~500만원' },
          { value: 'over_500', label: '500만원 이상 (공격적 마케팅)' },
        ],
      },
      {
        id: 'Q12', type: 'multiple_choice', required: true,
        question: '관심 있는 마케팅 서비스를 모두 선택해 주세요',
        options: [
          { value: 'naver_search_ad', label: '네이버 검색광고 (키워드/파워링크)' },
          { value: 'naver_place_ad', label: '네이버 플레이스 광고' },
          { value: 'naver_blog_mgmt', label: '네이버 블로그 운영 대행' },
          { value: 'google_search', label: '구글 검색 광고' },
          { value: 'google_display', label: '구글 디스플레이/유튜브 광고' },
          { value: 'meta_ad', label: '메타(페이스북/인스타) 광고' },
          { value: 'sns_mgmt', label: 'SNS 콘텐츠 제작 및 운영 대행' },
          { value: 'homepage', label: '홈페이지 제작/리뉴얼' },
          { value: 'seo', label: '검색엔진 최적화(SEO)' },
          { value: 'kakao_ad', label: '카카오 광고' },
          { value: 'consulting', label: '마케팅 전략 컨설팅만' },
        ],
      },
      {
        id: 'Q13', type: 'single_choice', required: true,
        question: '마케팅 대행을 맡길 의향이 있으신가요?',
        options: [
          { value: 'yes_all', label: '네, 전부 맡기고 싶다' },
          { value: 'yes_partial', label: '일부만 맡기고 싶다 (직접 참여하면서)' },
          { value: 'consult_first', label: '먼저 컨설팅/조언을 받고 싶다' },
          { value: 'diy', label: '직접 하고 싶은데 방법을 알고 싶다' },
          { value: 'undecided', label: '아직 모르겠다' },
        ],
      },
      {
        id: 'Q14', type: 'single_choice', required: true,
        question: '학원 홈페이지나 랜딩페이지가 있으신가요?',
        options: [
          { value: 'yes_good', label: '있고, 잘 관리되고 있다' },
          { value: 'yes_bad', label: '있지만 오래됐거나 관리가 안 된다' },
          { value: 'no_need', label: '없다 - 필요하다고 생각한다' },
          { value: 'no_noneed', label: '없다 - 없어도 된다고 생각한다' },
        ],
      },
      {
        id: 'Q15', type: 'single_choice', required: false,
        question: '경쟁 학원 대비 우리 학원의 가장 큰 강점은?',
        options: [
          { value: 'instructor', label: '강사진의 전문성/실력' },
          { value: 'curriculum', label: '차별화된 커리큘럼' },
          { value: 'result', label: '합격/성적 향상 실적' },
          { value: 'price', label: '합리적인 수강료' },
          { value: 'location', label: '편리한 위치/시설' },
          { value: 'care', label: '학생 개별 관리' },
          { value: 'brand', label: '브랜드/인지도' },
          { value: 'not_sure', label: '잘 모르겠다' },
        ],
      },
      {
        id: 'Q16', type: 'text', required: false,
        question: '마케팅 관련 특별히 고민 중이거나 전달하고 싶은 내용',
        placeholder: '예: 지난번에 네이버 광고를 해봤는데 효과가 없었어요...',
      },
    ],
  },
];

export const TOTAL_QUESTIONS = SURVEY_SECTIONS.reduce((acc, s) => acc + s.questions.length, 0);
